### ISSUE TITLE
DatePicker 日期选择 国际化有问题

### ISSUE THREAD

**Issue by guoqirong** [tea-design/tea-component#18]
DatePicker 日期选择 国际化有问题 中文星期显示英文了

**Comment by xughv** [comment]
感觉是项目构建时候把 moment 的中文支持给剔除掉了？比如 create-react-app 默认构建就有这个行为

**Comment by guoqirong** [comment]
那要怎么改，怎么修改组件 moment 的语言标识

**Comment by xughv** [comment]
`import 'moment/locale/zh-cn'`

引入后也不行吗

**Comment by guoqirong** [comment]
这个没有其他办法吗，我有多少语言就要import多少语言包太麻烦了吧

**Comment by xughv** [comment]
有啊，构建不要加类似这种配置 ..

https://github.com/facebook/create-react-app/blob/9802941ff049a28da2682801bc182a29761b71f4/packages/react-scripts/config/webpack.config.js#L696

或者忽略排除需要的语言
