### ISSUE TITLE
关于 tea-component-mobile 组件类型问题

### ISSUE THREAD

**Issue by SSShuai1999** [tea-design/tea-component#3]
您好！ 我们在使用  tea-component-mobile 组件库。在开发过程中，遇到了一些问题。

现象：

```ts
<Modal
    visible={visible}
    content={<>Sorry, no data yet. <br />Coming soon.</>}
    ....
 />
 ```
 上面组件中，`content` 类型得到了一个错误信息，不能将类型 `Element` 分配给类型 `string`。
 
 虽然如此，但是实际上运行是完全没有问题的。所以我觉得这应该是一个类型描述问题（确信）？
 
 期望：
 
 content 应该是 JSX.Element | string | undefined 的联合类型

**Comment by xughv** [comment]
装下最新版本试试呢，我看已经修正过类型了

https://unpkg.com/tea-component-mobile@0.3.9/lib/modal/Modal.d.ts

**Comment by SSShuai1999** [comment]
> 装下最新版本试试呢，我看已经修正过类型了
> 
> https://unpkg.com/tea-component-mobile@0.3.9/lib/modal/Modal.d.ts

谢谢您的及时回复，我们的问题得到了解决！
