### ISSUE TITLE
message提示的icon没有显示出来

### ISSUE THREAD

**Issue by hhhyyyy99** [tea-design/tea-component#32]
环境：
```
Node: 18.18.0
Electron: 31.2.1
React: 18.3.1
React-dom: 18.3.1
```
tea-component version: 2.8.0

main.ts 导入样式
```
import './assets/main.css'
import "tea-component/dist/tea.css";
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
```
App.tsx使用message
```
import {message} from "tea-component"

function App(): JSX.Element {
  return (
    <>
     <button onClick={()=>{
            message.success({
              content: 'Hello, Tea!',
              duration: 0,
            })
          }}>message</button>
    </> 
  )
}

export default App
```
最终效果呈现
<img width="900" alt="image" src="https://github.com/user-attachments/assets/5d27c80b-9251-453d-9457-2b1d54344ca8">

**Comment by hhhyyyy99** [comment]
最终呈现图
<img width="900" alt="image" src="https://github.com/user-attachments/assets/1b22ff57-a756-4891-b807-31c389af24f6">

**Comment by xughv** [comment]
2.8.0 的图标方案有变化，我们这里看下有什么问题

**Comment by xughv** [comment]
2.8.0 的样式实现依赖了 css 变量，当前只引入 `tea.css` 时图标默认颜色变量好像有缺失，我们会修正下。

可以从 `tea-component/dist/themes/` 下选择主题引入，并把 `tea.css` 换为 `tea-themeable.css`

**Comment by hhhyyyy99** [comment]
main.ts 重新引入之后，图标正常显示了，不过控制台有个error输出
```
import 'tea-component/dist/themes/default-light.css';
import "tea-component/dist/tea-themeable.css";
```
<img width="798" alt="image" src="https://github.com/user-attachments/assets/dff02934-5f7e-4521-9551-2145dfd3cbd6">

**Comment by xughv** [comment]
> main.ts 重新引入之后，图标正常显示了，不过控制台有个error输出
> 
> ```
> import 'tea-component/dist/themes/default-light.css';
> import "tea-component/dist/tea-themeable.css";
> ```
> 
> <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/80298668/351619116-dff02934-5f7e-4521-9551-2145dfd3cbd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDY3MzgsIm5iZiI6MTcyMTgwNjQzOCwicGF0aCI6Ii84MDI5ODY2OC8zNTE2MTkxMTYtZGZmMDI5MzQtNWY3ZS00NTIxLTk1NTEtMjE0NWRmZDNjYmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3MzM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MzI5Yjk1ODYzM2MwZjEyZDI0NTQxNjNlOTI2ZmEwMGQwMmY4OTI5ZGI5NDc2ZjlkNTJiMjQwNWI3MzZhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eL2zbi-KhHJ0vaBcLHHZAac9ibM4B7Pm0tqFr-Km6zs">

暂时没办法，还没有去完全兼容 React 18
