### ISSUE TITLE
可以按需引入吗？

### ISSUE THREAD

**Issue by jo-hnny** [tea-design/tea-component#4]

**Comment by xughv** [comment]
组件本身是支持 Tree Shaking 按需打包的，当前样式文件暂时不支持

**Comment by jo-hnny** [comment]
> 组件本身是支持 Tree Shaking 按需打包的，当前样式文件暂时不支持

需要使用babel-import-plugin吗？我看antd v4最新版好像是不需要配置的，
目前没有配置，按需引入好像没生效
![image](https://user-images.githubusercontent.com/15609400/125888209-c8bcb618-d659-45e5-bdfe-386972d6bd31.png)

**Comment by jo-hnny** [comment]
原因是在项目里混合使用了 import  from "tea-component/lib/xxx"
